package com.codingfeel.sm.dao;

import com.codingfeel.sm.model.MessageModel;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageModelDaoConfig;

    private final MessageModelDao messageModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageModelDaoConfig = daoConfigMap.get(MessageModelDao.class).clone();
        messageModelDaoConfig.initIdentityScope(type);

        messageModelDao = new MessageModelDao(messageModelDaoConfig, this);

        registerDao(MessageModel.class, messageModelDao);
    }

    public MessageModelDao getMessageModelDao() {
        return messageModelDao;
    }

}
